In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import json
import os

In [4]:
deg_file="/project/GCRB/Hon_lab/s426305/Analysis/IGVF/20240919_WTC11_lenti_CMProduction2/pySpade/Manhattan_plots/filtered_df.csv"
deg_unfiltered = pd.read_csv(deg_file,index_col=0)

In [5]:
json_fp = "./config.json"
with open(json_fp, 'r') as fp:
    config = json.load(fp)
    input_file = config["input_data"]["input_file"]
    
sgRNA_file = config["input_data"]["sgRNA_file"]

gRNA_dict_file = config["user_defined_data"]["gRNA_dict_file"]
pca_file = config["user_defined_data"]["pca_file"]
annotation_file = config["user_defined_data"]["annotation_file"]

annotation_df = pd.read_csv(annotation_file,index_col=0)
annotation_df.head()

,guide_chr,guide_start,guide_end,score,strand,protospacer_target,intended_target_region,gene_target,source,closest_gene,closest_dist,closest_gene_target,closest_dist_target
0,chr9,130713821,130713839,.,+,chr9:130713821-130713839(+),chr9:130713809-130714264,ABL1_ENST00000372348.2,"OpenTargets,CHDgene.au",ABL1,56,ABL1,56
1,chr9,130713809,130713827,.,+,chr9:130713809-130713827(+),chr9:130713809-130714264,ABL1_ENST00000372348.2,"OpenTargets,CHDgene.au",ABL1,56,ABL1,56
2,chr9,130713859,130713877,.,+,chr9:130713859-130713877(+),chr9:130713809-130714264,ABL1_ENST00000372348.2,"OpenTargets,CHDgene.au",ABL1,56,ABL1,56
3,chr9,130714246,130714264,.,-,chr9:130714246-130714264(-),chr9:130713809-130714264,ABL1_ENST00000372348.2,"OpenTargets,CHDgene.au",ABL1,56,ABL1,56
4,chr9,130713865,130713883,.,+,chr9:130713865-130713883(+),chr9:130713809-130714264,ABL1_ENST00000372348.2,"OpenTargets,CHDgene.au",ABL1,56,ABL1,56

In [6]:
deg_unfiltered.head()

,idx,gene_names,chromosome,pos,strand,color_idx,chr_idx,region,num_cell,bin,log(pval)-hypergeom,fc,Significance_score,fc_by_rand_dist_cpm,pval-empirical,cpm_perturb,cpm_bg
5809,44657,CPNE7,chr16,2490017985,+,1,15,chr11:63838685-63839185,5107,4000,-10.511666,0.620519,-11.017439,0.623012,0.0,5.727101,9.198647
8188,2738,HMGCS2,chr1,119768905,-,0,0,chr11:63838685-63839185,5107,4000,-7.158936,1.248243,-7.461287,1.253964,0.0,6.174064,4.921611
8197,2872,ITGA10,chr1,145910189,-,0,0,chr11:63838685-63839185,5107,4000,-7.948278,2.401094,-9.224782,2.402265,0.0,2.832810,1.173387
8224,3039,ECM1,chr1,150508062,+,0,0,chr11:63838685-63839185,5107,4000,-7.110753,1.697938,-7.466220,1.693692,0.0,2.580728,1.519634
8259,3213,S100A14,chr1,153616986,-,0,0,chr11:63838685-63839185,5107,4000,-8.385587,1.450902,-7.965464,1.461730,0.0,104.024020,71.161833

In [7]:
region_pos = annotation_df[annotation_df["gene_target"]=="LZTR1_P1P2"]["intended_target_region"].values[0]
print(region_pos)

chr22:20982302-20982395

In [8]:
deg_unfiltered_promoter = deg_unfiltered[deg_unfiltered["region"]==region_pos]

In [9]:
region_pos = annotation_df[annotation_df["gene_target"]=="Element866"]["intended_target_region"].values[0]
print(region_pos)

chr22:20971184-20971684

In [10]:
deg_unfiltered_enhancer = deg_unfiltered[deg_unfiltered["region"]==region_pos]

In [11]:
promoter_deg_top50 = deg_unfiltered_promoter.sort_values("Significance_score")["gene_names"].iloc[:100].values
enhancer_deg_top50 = deg_unfiltered_enhancer.sort_values("Significance_score")["gene_names"].iloc[:100].values

In [24]:
deg_unfiltered_enhancer[deg_unfiltered_enhancer["gene_names"]=="TSHZ2"]

Empty DataFrame
Columns: [idx, gene_names, chromosome, pos, strand, color_idx, chr_idx, region, num_cell, bin, log(pval)-hypergeom, fc, Significance_score, fc_by_rand_dist_cpm, pval-empirical, cpm_perturb, cpm_bg]
Index: []

In [25]:
deg_unfiltered_promoter[deg_unfiltered_promoter["gene_names"]=="TSHZ2"]

,idx,gene_names,chromosome,pos,strand,color_idx,chr_idx,region,num_cell,bin,log(pval)-hypergeom,fc,Significance_score,fc_by_rand_dist_cpm,pval-empirical,cpm_perturb,cpm_bg
9370191,52956,TSHZ2,chr20,2766001311,+,1,19,chr22:20982302-20982395,2146,2250,-141.0216,1.58639,-146.147231,1.588023,0.0,350.959417,221.000325

In [14]:
promoter_deg_top50

array(['TSHZ2', 'TMEM163', 'FBN2', 'IRX3', 'NRXN1', 'ADAMTSL1', 'CRABP2',
       'KDR', 'LAMA4', 'ETV5', 'POPDC2', 'CHRM2', 'KCNQ5', 'MASP1',
       'HAS2', 'COL13A1', 'SLIT2', 'DGKI', 'SORCS1', 'KCNH7', 'SLIT3',
       'TGM2', 'MYL3', 'A2M', 'MYOCD', 'SC5D', 'PDE4D', 'SLCO3A1',
       'LTBP1', 'SEMA3A', 'GFOD1', 'NRG3', 'PDGFD', 'ATP1A1', 'NUDT4',
       'ADAMTS1', 'CORIN', 'ESRRG', 'ACTA2', 'BMPER', 'SLC8A3', 'P3H2',
       'FABP5', 'ADAMTS3', 'NAV2', 'ABTB2', 'CRNDE', 'VSTM2L', 'RGS5',
       'G0S2', 'PCDH7', 'SMYD1', 'CTNNA3', 'TIAM1', 'HTRA1', 'AHNAK2',
       'SPRY4', 'COL5A1', 'PALLD', 'ALPK2', 'PLXNA4', 'LHX1', 'SORBS2',
       'NES', 'FHL2', 'S100A10', 'DACH1', 'ATP13A3', 'PTPRG', 'CKB',
       'ADCY5', 'PRKCH', 'SVIL', 'IRX5', 'CAPN3', 'MAN1C1', 'TIMP3',
       'PSD3', 'PAM', 'MAST4', 'PRKAG2', 'MEF2C', 'PPM1K', 'MICAL2',
       'MTUS2', 'ELL2', 'TGFB2', 'MEIS2', 'WNT5B', 'SMPX', 'HRC', 'AAK1',
       'ITGAV', 'GJA3', 'RASAL2', 'EPHA3', 'TRPC3', 'BICC1', 'SCMH1',
       'GYPC'], dtype=object)

In [15]:
enhancer_deg_top50

array(['TGM2', 'PRKCH', 'XKR6', 'NPPA', 'XIRP1', 'TTC19', 'CREBBP',
       'TRAPPC9', 'DHTKD1', 'SDC3', 'RNF144A', 'MCPH1', 'VPS52',
       'FAM168A', 'WDR7', 'INVS', 'ADCY5', 'PARL', 'NDRG4', 'ATXN7L3',
       'BCL9L', 'PPWD1', 'GPRIN3', 'C5orf63', 'NPPB', 'ZNF211', 'KIF7',
       'TMEM41A', 'CXCL12', 'TYSND1', 'CUX2', 'KIF9', 'HIVEP2', 'MOK',
       'FAM83H', 'PRRG3', 'PIEZO2', 'CES2', 'AKAP6', 'SLC25A23', 'ZNF236',
       'CIPC', 'KLHL13', 'GAA', 'CYP26A1', 'DNAH14', 'HHATL', 'DNAH3',
       'MPHOSPH6', 'EXTL2', 'ZXDB', 'SLCO5A1', 'TARBP1', 'H19', 'TCF21',
       'GART', 'ADAMTS3', 'ADIPOR2', 'ODAM', 'TAL2', 'C18orf54',
       'FAM153B', 'SGTA', 'SCLY', 'AC067945.4', 'PYROXD1', 'MIR100HG',
       'COMMD2', 'FST', 'SORCS2', 'ANKS3', 'COQ10B', 'ABCA3', 'PRODH',
       'RAB4B', 'METTL18', 'MIR34AHG', 'KITLG', 'GRAMD4', 'PHF11'],
      dtype=object)

In [16]:
set(promoter_deg_top50) & set(enhancer_deg_top50)

{'ADAMTS3', 'ADCY5', 'PRKCH', 'TGM2'}

In [83]:
deg_unfiltered_promoter

,idx,gene_names,chromosome,pos,strand,color_idx,chr_idx,region,num_cell,bin,log(pval)-hypergeom,fc,Significance_score,fc_by_rand_dist_cpm,pval-empirical,cpm_perturb,cpm_bg
18588794,59,SAMD11,chr1,923928,+,0,0,chr12:114405669-114406173,1858,1750,-1.632844,0.994386,-1.593645,0.994632,0.191,32.992615,33.170733
18588795,62,PLEKHN1,chr1,966497,+,0,0,chr12:114405669-114406173,1858,1750,-1.658004,0.366596,-1.477148,0.374064,0.197,0.185807,0.513459
18588796,73,RNF223,chr1,1074307,-,0,0,chr12:114405669-114406173,1858,1750,-1.281548,0.642573,-2.070720,0.630718,0.293,0.149131,0.242301
18588797,85,B3GALT6,chr1,1232265,+,0,0,chr12:114405669-114406173,1858,1750,-0.674969,0.983154,-0.589707,0.991332,0.569,17.626008,17.780209
18588798,88,UBE2J2,chr1,1273885,-,0,0,chr12:114405669-114406173,1858,1750,-1.074559,0.954982,-1.049889,0.956599,0.324,40.972529,42.831904
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18604570,57872,PRKY,chrY,3038316389,+,1,23,chr12:114405669-114406173,1858,1750,-3.233567,6.256764,-3.315476,5.536825,0.048,0.092843,0.008574
18604571,58001,USP9Y,chrY,3043743648,+,1,23,chr12:114405669-114406173,1858,1750,-1.231110,1.067121,-1.151260,1.067674,0.276,94.067141,88.104093
18604572,58003,DDX3Y,chrY,3043946525,+,1,23,chr12:114405669-114406173,1858,1750,-2.373305,1.123371,-2.181537,1.125093,0.072,84.259864,74.890385
18604573,58016,NLGN4Y,chrY,3045564990,+,1,23,chr12:114405669-114406173,1858,1750,-1.149483,1.149711,-1.185343,1.148384,0.311,44.036638,38.345334
18604574,58084,AC022486.1,chrY,3049534157,+,1,23,chr12:114405669-114406173,1858,1750,-0.852919,1.436626,-3.478691,1.538072,0.379,0.162259,0.101997