In [2]:
import os
import re
import sys

import itertools 
import scipy
import matplotlib
import glob
%matplotlib inline
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
import scipy.sparse as sp_sparse
import scipy.io as sio
import matplotlib.mlab as mlab

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from multiprocessing import Pool
from collections import defaultdict
from scipy import sparse
from scipy.sparse import csr_matrix
from scipy.cluster.hierarchy import dendrogram, linkage
import scipy.io as io

In [3]:
global_df = pd.read_csv('/project/GCRB/Hon_lab/s426305/Analysis/IGVF/20240219_WTC11_TFPerturb_CM-full_all/pySpade/Manhattan_plots/filtered_df.csv')

In [4]:
global_df.shape

(27578, 18)

In [5]:
#Load annotation file 
annot_dict_file = '/project/GCRB/Hon_lab/s426305/Analysis/IGVF/20240219_WTC11_TFPerturb_CM-full_all/pySpade/annotation_dict_hg38.txt'
annot_dict = {}
with open(annot_dict_file) as f:
    for line in f:
        region_id, annotation = line.strip().split("\t")
        annot_dict.update({region_id : annotation})

In [6]:
TF_region_df = pd.DataFrame.from_dict(annot_dict, columns=['TF'], orient='index')

In [7]:
TF_global_df = global_df[global_df['gene_names'].isin(TF_region_df['TF'])]

In [8]:
TF_global_df.shape

(3010, 18)

In [10]:
rank_TF_list = [annot_dict[i[0]] for i in collections.Counter(TF_global_df['region']).most_common()]

###  RE df

In [11]:
df_column_list = [
        'idx', 'gene_names', 'chromosome', 'pos', 'strand', 
        'color_idx', 'chr_idx', 
        'region', 'num_cell', 'bin',
        'log(pval)-hypergeom', 'fc', 'Significance_score', 'fc_by_rand_dist_cpm', 'pval-empirical', 'cpm_perturb', 'cpm_bg']

In [12]:
GLBOAL_HITS = '/project/GCRB/Hon_lab/s426305/Analysis/IGVF/20241209_WTC11_lenti_TFPerturb_RE/pySpade/unfiltered_global_df.csv'

In [13]:
FILE_DIR = '/project/GCRB/Hon_lab/s426305/Analysis/IGVF/20241209_WTC11_lenti_TFPerturb_RE/pySpade/'

In [14]:
#Load unfilter global hits df 
global_df = pd.read_csv(GLBOAL_HITS)[df_column_list]

In [15]:
CUTOFF_EXP = 0.05
CUTOFF_FC = 0.1
CUTOFF_SIG = -10

In [16]:
#Load expressed genes 
gene_seq = np.load(FILE_DIR + 'Trans_genome_seq.npy', allow_pickle=True)
express_level = np.load(FILE_DIR + 'Perc_cell_expr.npy')
express_idx = np.where(express_level > CUTOFF_EXP)[0]

In [17]:
#filter df 
express_df = global_df[global_df['gene_names'].isin(gene_seq[express_idx])\
                  &((global_df['fc_by_rand_dist_cpm'] > (1+CUTOFF_FC)) | (global_df['fc_by_rand_dist_cpm'] < (1-CUTOFF_FC)))\
                  &(global_df['Significance_score'] < CUTOFF_SIG)\
                  &(global_df['pval-empirical'] < 0.001)
                  &(global_df['log(pval)-hypergeom'] < -3)]

In [30]:
express_df['TF_annotation'] = [annot_dict[i] for i in express_df['region']] 
TF_global_df['TF_annotation'] = [annot_dict[i] for i in TF_global_df['region']]

/tmp/ipykernel_62792/3074219906.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  express_df['TF_annotation'] = [annot_dict[i] for i in express_df['region']]

In [19]:
RE_annotation_df = pd.read_csv('/project/GCRB/Hon_lab/s159317/IGVF/scTE_mapping/CM.TF-Perturb-Seq/temp/rmsk.txt', sep='\t', 
                           names=['1', '2', '3', '4', '5', 'chr', 'start', 'end', 'pos', 'strand', 'name', 'cate', 'names', '6', '7', '8', '9'])

In [20]:
RE_annotation_df.head()

,1,2,3,4,5,chr,start,end,pos,strand,name,cate,names,6,7,8,9
0,585,463,13,6,17,chr1,10000,10468,-248945954,+,(TAACCC)n,Simple_repeat,Simple_repeat,1,471,0,1
1,585,3612,114,215,13,chr1,10468,11447,-248944975,-,TAR1,Satellite,telo,-399,1712,483,2
2,585,484,251,132,0,chr1,11504,11675,-248944747,-,L1MC5a,LINE,L1,-2382,395,199,3
3,585,239,294,19,10,chr1,11677,11780,-248944642,-,MER5B,DNA,hAT-Charlie,-74,104,1,4
4,585,318,230,37,0,chr1,15264,15355,-248941067,-,MIR3,SINE,MIR,-119,143,49,5

In [21]:
subset_express_df = express_df[(express_df['gene_names'].isin(RE_annotation_df['name']))]

In [34]:
np.unique(subset_express_df["TF_annotation"]).shape

(423,)

In [22]:
RE_TF_list = [i[0] for i in collections.Counter(subset_express_df['TF_annotation']).most_common()]

In [31]:
for i in RE_TF_list:
    TF_common = set(TF_global_df[TF_global_df['TF_annotation'] == i]['gene_names']).intersection(set(RE_TF_list))
    print(i + '\t' + str(TF_common))

TCF7	{'TSHZ2', 'IRX3', 'MYOCD', 'CREM', 'ESRRG'}
ZNF630	set()
DMRTA1	set()
ESRRG	{'ESRRG'}
NR1H3	set()
FOXG1	set()
HELT	set()
ZBTB21	{'GATA5'}
CPEB1	set()
ZMAT2	set()
GLI3	{'HAND1', 'GLI3', 'FOXK1'}
ZNF449	set()
LHX1	set()
ZFP64	{'ZFP64', 'HAND1', 'HOXB4', 'HOXB2', 'KMT2A', 'ESRRG', 'MSX2'}
TBPL1	set()
ZNF276	{'ZNF276'}
SPIC	set()
CSRNP3	{'CSRNP3'}
FOXE1	set()
LCORL	{'LCORL'}
SP110	{'MYOCD'}
BAZ1B	{'IRX3', 'BAZ1B', 'TCERG1'}
MYT1	set()
HIRA	set()
ZNF202	{'ZNF202'}
ZNF30	{'ZNF30'}
REXO4	{'REXO4'}
ZNF805	set()
ZNF532	{'EGR1', 'ZNF141', 'ESRRG', 'ZNF532'}
BSX	set()
ZNF649	{'ZNF649'}
ZNF628	set()
GAS7	{'GAS7'}
IKZF2	{'IKZF2'}
CHAMP1	{'CREB5', 'JUN', 'TBX18', 'CHAMP1', 'ESRRG'}
RFX7	{'SMAD7'}
KMT2A	{'SOX6', 'HOXB4', 'TBX18', 'KMT2A', 'ESRRG'}
ZNF880	{'ZNF880'}
LZTS1	set()
OR2T5	set()
CENPB	{'CENPB'}
HES6	set()
TCEB2	set()
FUBP3	{'FUBP3'}
ZNF431	{'ZNF431'}
ZNF561	{'ZNF561'}
HOXC6	set()
ZNF679	set()
ZNF562	set()
TADA2B	{'ZNF385A', 'EEA1', 'NR4A3', 'TBX18', 'SOX6', 'PHTF1', 'MYOCD', 'NCOA6', 'LMX1B', 'FOXF1', 'SOX4', 'GLI3', 'EGR1', 'ZBTB38', 'LHX1'}
SOX11	{'TSHZ2', 'SOX11', 'FOSB', 'TBX20', 'IRX3', 'SMAD3', 'ZNF880', 'MYOCD', 'TGIF1', 'CDCA7L', 'ZNF451', 'FOXF1', 'SP110', 'SMAD2', 'LMO3', 'EGR1', 'PIAS3'}
MXI1	set()
HMX1	set()
CREM	{'CREM'}
OR2T6	set()
HOXC5	set()
ZNF782	set()
ZNF608	{'TSHZ2', 'LHX8', 'IRX3', 'ZNF608', 'ESRRG'}
HOXB4	{'TSHZ2', 'TBX20', 'SOX6', 'MYOCD', 'HOXB4', 'TBX18', 'ESRRG'}
FOXP3	set()
ZHX2	{'ZHX2'}
ZNF850	{'ZNF850'}
PRKRIP1	{'PRKRIP1'}
BACH1	{'BACH1'}
HAND2	{'TSHZ2', 'HAND2', 'ESRRG'}
TP53	{'TP53', 'TBX18', 'HHEX'}
E2F7	set()
ZFPM2	{'GLIS3', 'JUN', 'ZFPM2', 'ADNP2', 'CREM', 'HOXB4', 'EGR1'}
ZNF397	set()
ZC3H3	{'TP53', 'ZNF606', 'ZNF429', 'ZNF141'}
TBX20	{'GATA5', 'SMAD7', 'HAND2', 'SMAD3', 'SP6', 'ERG', 'GLI3', 'ARID5B', 'MIXL1', 'HOXB4', 'TBX18', 'MLLT3', 'E2F7', 'HHEX', 'IRF6', 'HES6', 'MSX2', 'ZNF703', 'TBX20', 'FOXL1', 'MYOCD', 'SOX4', 'HOXB2'}
GATAD1	{'XRCC6', 'GATAD1', 'EEA1'}
RXRA	set()
HOXA3	{'ZNF629'}
ZFP90	{'ZFP90'}
ZNF394	{'ZNF394'}
JUN	{'JUN'}
ZNF320	{'ZNF320'}
ZNF268	{'ZNF268'}
ZNF253	{'LHX6', 'ZNF253'}
CPXCR1	set()
RCOR2	{'TSHZ2', 'ZNF350', 'GAS7', 'FOSB', 'SP6', 'MYOCD', 'ARID5B', 'HAND1', 'HOXB4', 'HOPX', 'FOXF1', 'ZFP42', 'TBX18', 'EGR1', 'RCOR2'}
FOXL1	{'NR4A3'}
SMAD2	{'HAND2', 'MSX2', 'SMAD2'}
HAND1	{'LHX8', 'CREB5', 'ZNF385A', 'IRX3', 'HAND1', 'CDCA7L', 'ZNF611', 'NFIA'}
HOPX	set()
FBXL19	{'FBXL19'}
BAZ2A	{'BAZ2A', 'PHTF1'}
ZBTB25	{'ZBTB25'}
Positve control	set()
AFF4	{'AFF4'}
HSFX12	set()
CLOCK	{'CLOCK'}
ZNF91	{'OXSR1', 'ZNF91', 'NR4A3'}
GMEB1	set()
MIXL1	{'GLI3', 'ZNF195'}
TFDP2	{'TFDP2'}
FOXK1	{'FOXK1'}
TGIF1	set()
GFI1	set()
ZBTB48	{'ZBTB48'}
TULP3	{'TULP3'}
EEA1	{'EEA1'}
RUNX2	set()
ZNF235	{'ZNF235'}
AHDC1	set()
ZNF211	set()
ZSCAN22	set()
ZNF160	{'ZNF160'}
ZKSCAN1	{'ZKSCAN1'}
MLLT10	{'ESRRG', 'MLLT10'}
ZNF644	{'ZNF644'}
CDIP1	{'CDIP1'}
RUNX3	set()
SAFB2	{'SP140', 'SAFB2'}
ZNF878	set()
RARA	{'HOPX'}
VENTX	set()
HMGB1	set()
ARID4B	{'IRX3', 'ARID4B', 'RBPJ'}
ZNF566	{'ZNF566'}
ZNF81	set()
TBX18	{'TBX18'}
FOSB	set()
ELMSAN1	set()
ZNF408	{'ZNF408'}
RFXAP	set()
KAT7	{'ESRRG', 'SOX6', 'KAT7'}
ZNF480	{'ZNF480'}
ZNF195	{'ZNF195', 'TSHZ2'}
GATA4	{'GAS7', 'NKX2-6', 'HAND1', 'TBX18', 'MSX2'}
ZNF329	{'ZNF420'}
ASCL4	set()
ZNF141	{'ZNF141'}
NCOA6	{'NCOA6'}
ZFP42	set()
SPZ1	set()
GATA1	set()
ADNP2	{'ADNP2', 'ZNF280D', 'ZNF880'}
SMYD2	{'SMYD2'}
ZNF629	{'HAND1', 'ZNF629'}
ZNF177	set()
GZF1	set()
ZNF705B	set()
THAP9	{'THAP9'}
ZNF845	set()
SOX6	set()
SOX21	set()
CARHSP1	{'CARHSP1'}
CUX1	set()
RBPJ	{'RBPJ'}
NANOGNB	{'ILF3'}
GSC2	set()
ARHGAP35	set()
NR2F6	{'NFIA'}
ARID2	{'LHX8', 'ZNF397', 'HAND2', 'JUN', 'ZNF658', 'HAND1', 'ZNF91', 'ZNF608', 'ZNF646', 'ARID2'}
ZNF454	set()
NFKBIA	{'NFKBIA'}
MSX2	{'MSX2'}
ZNF292	{'ZNF292', 'ALX3', 'SMAD2'}
ZFP82	{'ZFP82'}
ZNF621	{'ZNF621'}
NCOR2	set()
BATF3	set()
ZNF326	{'ZNF326'}
ZNF490	{'ZNF490'}
MXD3	set()
SMYD3	{'SMYD3'}
ZNF620	{'ZNF620'}
ZHX1	{'ZHX1'}
TGIF2LX	set()
AHR	set()
TCEB3	{'HAND1'}
ZBTB38	{'ZBTB38'}
CNBP	{'CNBP'}
PLAGL2	{'TBX18', 'SOX6', 'PLAGL2'}
ZNF582	set()
SOX4	{'TBX18', 'TSHZ2', 'EGR1', 'SOX4'}
HLF	set()
GLIS3	{'GLIS3'}
TOPORS	{'TOPORS'}
ZNF460	{'GLI3', 'ZFP42', 'ZNF460'}
ZBTB42	{'ZBTB42'}
ALX3	set()
APITD1	{'IRX3'}
TBX15	set()
ZNF837	set()
NR4A3	{'NR4A3'}
ZNF197	set()
CRTC2	set()
PCGF2	{'TBX18', 'PCGF2'}
ZNF439	{'ZNF439'}
ARNTL2	set()
CDCA7L	{'CDCA7L'}
ZNF226	{'ZNF226'}
SP6	{'SP6'}
ZNF385A	set()
GATA5	{'GATA5'}
ZNF251	{'ZNF251'}
IRF3	{'IRF3'}
MYCL	set()
ZNF799	set()
MBD1	{'TSHZ2', 'MBD1', 'ZNF611'}
ZNF831	set()
ZNF286A	{'ZNF286A'}
ZNF517	{'ZFP1'}
ZNF146	{'ZNF146', 'ZNF565'}
ZNF446	set()
OXSR1	{'OXSR1'}
DBX1	{'HIRA'}
ZNF746	{'ZNF746'}
ZNF606	{'ZNF606', 'PHF21A'}
NOTO	{'IRX3'}
ZNF839	{'ZNF839'}
ZNF445	{'ZNF445'}
ZFP69B	set()
PSMB4	set()
ERG	set()
GLI2	set()
NCL	set()
ALYREF	set()
ILF3	{'ILF3'}
TSHZ2	{'TSHZ2'}
EGR1	set()
NANOG	set()
WDR82	set()
XRCC6	set()
ZNF365	set()
HDAC3	set()
ZNF703	set()
FOXO4	set()
TCERG1	set()
SP2	set()
PSMC3	set()
ZNF646	set()
ZNF200	{'ZNF880', 'ZNF200'}
ZNF23	{'ZNF23'}
TEAD2	{'TEAD2'}
ZNF451	{'ZNF451'}
DMRTA2	set()
KCNIP3	set()
NOTCH1	{'JUN'}
ZXDB	set()
ZNF331	{'TSHZ2', 'GAS7'}
ZNF280D	{'ZNF280D'}
PTF1A	set()
LZTR1	{'TSHZ2', 'IRX3', 'LZTR1', 'MYOCD', 'EGR1', 'ESRRG'}
ZNF41	{'ZNF41'}
ZNF382	{'ZNF382'}
ZNF565	{'ZNF146', 'ZNF565'}
DPF1	set()
ZIM2	set()
PHF21A	{'PHF21A', 'HOXB4', 'MSX2'}
FEV	set()
ZNF80	set()
THAP2	{'KAT7', 'THAP2'}
CSNK2A1	{'CSNK2A1'}
TAF10	set()
RLF	{'RLF'}
PATZ1	set()
E2F4	set()
ZNF786	set()
CREB3L3	set()
SP3	set()
MBD2	set()
CBX2	set()
L3MBTL1	{'L3MBTL1'}
OR5M8	set()
CDX2	set()
ZNF534	set()
POGK	{'POGK'}
TET3	set()
ZNF311	set()
HOXB2	{'HOXB2'}
NEUROD4	set()
ARID5B	set()
ZNF414	{'ZNF414'}
ZSCAN32	set()
NKX3-2	set()
ZNF257	{'TSHZ2'}
FOXD2	set()
KLF15	set()
LMX1B	set()
MESP2	set()
ZBTB4	set()
ZNF236	{'LHX8'}
CBFA2T3	set()
ZBTB20	{'ZBTB20'}
RHOXF2B	set()
ZNF658	set()
TLX2	set()
HMGN3	{'HMGN3'}
PRDM8	set()
IRF6	set()
BHLHA15	set()
PIN1	{'ZNF302', 'TSHZ2', 'IRX3', 'MYOCD', 'PIN1', 'TBX18'}
DLX3	{'ZNF805'}
MSANTD4	{'MSANTD4'}
LDB1	{'LDB1'}
MLLT3	{'MLLT3'}
FOXN4	set()
ZNF500	{'ZNF500'}
ZNF689	{'ZNF689'}
ZFP1	{'ZFP1'}
SMAD3	{'SMAD3', 'HOXB4'}
HSF4	set()
PAX3	set()
PAWR	{'PAWR'}
ZNF14	set()
ZIK1	{'ZIK1'}
MYOD1	set()
MYOCD	{'ERG', 'MLLT3', 'MYOCD'}
PHOX2A	set()
PBX4	{'PBX4'}
SOX30	set()
ZNF611	{'ZNF611'}
SMAD5	{'MLLT3', 'HAND1', 'SMAD5', 'SMAD2', 'TBX18', 'EGR1'}
EMX1	set()
ZNF750	set()
MEIS1	{'TSHZ2', 'RBPJ', 'IRX3', 'SOX6', 'MEIS1', 'ZNF79', 'TBX18', 'ESRRG'}
ZNF853	set()
NR2E1	set()
IKZF1	set()
CCDC17	set()
OR5AK2	set()
NKX2-6	{'NKX2-6'}
ZSCAN20	set()
KLF8	set()
TIGD2	set()
HOXA5	set()
ZNF182	set()
SP140	set()
TEF	{'TEF'}
ZNF497	set()
OR2A2	set()
ETV3L	set()
CREB5	set()
ZNF736	set()
ZNF350	set()
ZNF260	{'ZNF260'}
OR5A2	set()
HNF4G	set()
ZNF264	set()
IRX3	set()
ZNF705G	set()
ZNF526	set()
LMO3	{'LMO3'}
OR12D2	set()
ZNF436	{'IRX3', 'ZNF436'}
HOXA10	set()
PIAS3	set()
ZNF319	set()
ZNF547	set()
HEYL	set()
ZNF425	set()
POU2AF1	set()
ZNF429	{'ZNF429'}
BAZ2B	{'BAZ2B'}
LIN54	set()
ZNF507	{'ZNF507'}
ZNF154	{'ZNF154'}
ELF1	set()
UNCX	{'TBX18'}
GLIS2	set()
OR2AE1	set()
ZNF189	{'ZNF189'}
NFIA	{'NFIA'}
PROX1	{'PROX1', 'BAZ2A'}
ZNF462	{'ZNF462', 'ZNF608'}
ZKSCAN4	set()
ZNF223	set()
ZNF626	{'ZNF626'}
SRY	set()
POU2F3	set()
SIRT6	{'SIRT6'}
MAZ	set()
HSF2	{'HSF2'}
ZNF273	set()
ZNF302	{'ZNF302'}
OR2T33	{'ZHX1'}
OR14J1	{'GAS7'}
LHX8	set()
OR5T3	set()
VAX1	set()
TRIM28	set()
TCF24	set()
ZNF79	set()
SMAD7	set()
HOXA6	set()
POU2F2	set()
TFDP3	set()
ARGFX	set()
ZNF426	{'ZNF426', 'ZNF839'}
ZBTB46	{'RUNX3'}
ZNF768	{'ZNF768'}
PHTF1	{'PHTF1'}
ZNF214	set()
ZNF730	set()
OR4B1	set()
MAEL	set()
OR8B8	set()
SP4	{'SP4'}
CREB3	set()
ZBTB37	set()
FERD3L	set()
TNXB	set()
ZFHX3	set()
ZNF844	{'ZNF844', 'MYOCD'}
ZNF33B	{'ZNF33B'}
MLXIPL	set()
OR51F2	set()
PRRX2	{'PRRX2'}
ZNF420	{'ZNF420'}
POU4F3	set()
LHX6	set()
ZNF595	{'ZNF595'}
HHEX	set()
TFAP2E	set()
FOXF1	set()
FIGLA	{'GATA5'}
ZNF442	set()
ZNF572	set()
OR5M1	set()

In [35]:
subset_express_df

,idx,gene_names,chromosome,pos,strand,color_idx,chr_idx,region,num_cell,bin,log(pval)-hypergeom,fc,Significance_score,fc_by_rand_dist_cpm,pval-empirical,cpm_perturb,cpm_bg,TF_annotation
128561,62842,MER34A1,NaN,NaN,+,0,24,chr14:35403160-35403255,788,800,-10.402540,2.150119,-10.139871,2.133280,0.0,13.600745,6.370198,NFKBIA
234932,67935,AluSq,NaN,NaN,+,0,24,chr15:82647585-82648021,850,800,-10.200421,1.181449,-10.711242,1.180137,0.0,332.989151,282.159954,CPEB1
234939,79974,AluSx4,NaN,NaN,+,0,24,chr15:82647585-82648021,850,800,-11.814065,1.235187,-11.745783,1.232939,0.0,185.153446,150.170547,CPEB1
238945,80427,Kanga1a,NaN,NaN,+,0,24,chr15:82647585-82648021,850,800,-9.228898,1.394545,-10.311442,1.402169,0.0,17.230537,12.285619,CPEB1
238949,73752,L1M2,NaN,NaN,+,0,24,chr15:82647585-82648021,850,800,-10.671792,1.156556,-10.940925,1.155351,0.0,268.157090,232.098763,CPEB1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45020253,79314,Ricksha,NaN,NaN,+,0,24,chr5:178941224-178941469,572,600,-9.093342,2.468002,-10.017832,2.486340,0.0,6.778835,2.720453,ZNF454
45188299,81638,HERVL-int,NaN,NaN,+,0,24,chr2:70790394-70790673,562,600,-9.168361,1.337419,-10.665309,1.342354,0.0,53.180660,39.614912,FIGLA
45404080,81824,LTR57-int,NaN,NaN,+,0,24,chr19:12365551-12365666,588,600,-8.606282,3.110194,-10.093491,3.099913,0.0,6.296399,2.024379,ZNF442
45447788,80555,LTR91,NaN,NaN,+,0,24,chr8:124973307-124973501,662,600,-8.882677,4.109250,-12.029823,4.234418,0.0,5.592406,1.313064,ZNF572
45579231,87087,X7D_LINE,NaN,NaN,+,0,24,chr11:56613001-56614001,595,600,-3.911901,4.551164,-11.144191,4.380808,0.0,1.218590,0.270448,OR5M1